---

- name: Scaling Backup Container {{ SSO_BACKUP_NAME }} to 1 Pods
  shell: oc -n {{ TARGET_NAMESPACE }} scale dc/{{ SSO_BACKUP_NAME }} --replicas=1

- name: Waiting for Backup Container to be scaled up
  include_tasks: ../../ops/tasks/wait_for_scale_up.yml
  vars:
    KIND: DeploymentConfig
    OBJECT_NAME: "{{ SSO_BACKUP_NAME }}"